import React from 'react'

export const ThreeColumnLayout = () => {
  return (
    <div className="flex flex-row mt-[4em]">
        <div className="flex flex-col border-2 border-black h-screen w-[20vw]">

        </div>
        <div className="flex flex-col border-2 border-black h-screen w-[60vw] overflow-y-auto">
        The Holocaust was the genocide of European Jews during World War II. Between 1941 and 1945, Nazi Germany and its collaborators systematically murdered some six million Jews across German-occupied Europe, around two-thirds of Europe's Jewish population. The murders were carried out primarily through mass shootings and poison gas in extermination camps, chiefly Auschwitz-Birkenau, Treblinka, Belzec, Sobibor, and Chełmno in occupied Poland.

The Nazis developed their ideology based on racism and pursuit of "living space" and seized power in early 1933. In an attempt to force all German Jews to emigrate, the regime passed anti-Jewish laws and orchestrated a nationwide pogrom in November 1938. After Germany invaded Poland in September 1939, occupation authorities began to establish ghettos to segregate Jews. Following the invasion of the Soviet Union in June 1941, around 1.5 to 2 million Jews were shot by German forces and local collaborators.

Later in 1941 or early 1942, the highest levels of the German government decided to murder all Jews throughout Europe. Victims were deported by rail to extermination camps where, if they survived the journey, most were killed with poison gas. Other Jews continued to be employed in forced labor camps where many died from starvation, abuse or exhaustion[2] or used as test subjects in deadly medical experiments.[3] Although many Jews tried to escape, surviving in hiding was very difficult due to factors such as the lack of money to pay helpers and the risk of denunciation. The property, homes, and jobs belonging to murdered Jews were redistributed to the German occupiers and other non-Jews. Although the majority of Holocaust victims died in 1942, the killing continued at a lower rate until the end of the war in May 1945. Not all victims were Jews however, with millions killed for ethnic and ideological associations.

Many Jewish survivors emigrated outside of Europe after the war. A few Holocaust perpetrators faced criminal trials. Billions of dollars in reparations have been paid, although falling short of the Jews' losses. The Holocaust has also been commemorated in museums, memorials, and culture. It has become central to Western historical consciousness as a symbol of the ultimate human evil.
The Holocaust was the genocide of European Jews during World War II. Between 1941 and 1945, Nazi Germany and its collaborators systematically murdered some six million Jews across German-occupied Europe, around two-thirds of Europe's Jewish population. The murders were carried out primarily through mass shootings and poison gas in extermination camps, chiefly Auschwitz-Birkenau, Treblinka, Belzec, Sobibor, and Chełmno in occupied Poland.

The Nazis developed their ideology based on racism and pursuit of "living space" and seized power in early 1933. In an attempt to force all German Jews to emigrate, the regime passed anti-Jewish laws and orchestrated a nationwide pogrom in November 1938. After Germany invaded Poland in September 1939, occupation authorities began to establish ghettos to segregate Jews. Following the invasion of the Soviet Union in June 1941, around 1.5 to 2 million Jews were shot by German forces and local collaborators.

Later in 1941 or early 1942, the highest levels of the German government decided to murder all Jews throughout Europe. Victims were deported by rail to extermination camps where, if they survived the journey, most were killed with poison gas. Other Jews continued to be employed in forced labor camps where many died from starvation, abuse or exhaustion[2] or used as test subjects in deadly medical experiments.[3] Although many Jews tried to escape, surviving in hiding was very difficult due to factors such as the lack of money to pay helpers and the risk of denunciation. The property, homes, and jobs belonging to murdered Jews were redistributed to the German occupiers and other non-Jews. Although the majority of Holocaust victims died in 1942, the killing continued at a lower rate until the end of the war in May 1945. Not all victims were Jews however, with millions killed for ethnic and ideological associations.

Many Jewish survivors emigrated outside of Europe after the war. A few Holocaust perpetrators faced criminal trials. Billions of dollars in reparations have been paid, although falling short of the Jews' losses. The Holocaust has also been commemorated in museums, memorials, and culture. It has become central to Western historical consciousness as a symbol of the ultimate human evil.
The Holocaust was the genocide of European Jews during World War II. Between 1941 and 1945, Nazi Germany and its collaborators systematically murdered some six million Jews across German-occupied Europe, around two-thirds of Europe's Jewish population. The murders were carried out primarily through mass shootings and poison gas in extermination camps, chiefly Auschwitz-Birkenau, Treblinka, Belzec, Sobibor, and Chełmno in occupied Poland.

The Nazis developed their ideology based on racism and pursuit of "living space" and seized power in early 1933. In an attempt to force all German Jews to emigrate, the regime passed anti-Jewish laws and orchestrated a nationwide pogrom in November 1938. After Germany invaded Poland in September 1939, occupation authorities began to establish ghettos to segregate Jews. Following the invasion of the Soviet Union in June 1941, around 1.5 to 2 million Jews were shot by German forces and local collaborators.

Later in 1941 or early 1942, the highest levels of the German government decided to murder all Jews throughout Europe. Victims were deported by rail to extermination camps where, if they survived the journey, most were killed with poison gas. Other Jews continued to be employed in forced labor camps where many died from starvation, abuse or exhaustion[2] or used as test subjects in deadly medical experiments.[3] Although many Jews tried to escape, surviving in hiding was very difficult due to factors such as the lack of money to pay helpers and the risk of denunciation. The property, homes, and jobs belonging to murdered Jews were redistributed to the German occupiers and other non-Jews. Although the majority of Holocaust victims died in 1942, the killing continued at a lower rate until the end of the war in May 1945. Not all victims were Jews however, with millions killed for ethnic and ideological associations.

Many Jewish survivors emigrated outside of Europe after the war. A few Holocaust perpetrators faced criminal trials. Billions of dollars in reparations have been paid, although falling short of the Jews' losses. The Holocaust has also been commemorated in museums, memorials, and culture. It has become central to Western historical consciousness as a symbol of the ultimate human evil.
The Holocaust was the genocide of European Jews during World War II. Between 1941 and 1945, Nazi Germany and its collaborators systematically murdered some six million Jews across German-occupied Europe, around two-thirds of Europe's Jewish population. The murders were carried out primarily through mass shootings and poison gas in extermination camps, chiefly Auschwitz-Birkenau, Treblinka, Belzec, Sobibor, and Chełmno in occupied Poland.

The Nazis developed their ideology based on racism and pursuit of "living space" and seized power in early 1933. In an attempt to force all German Jews to emigrate, the regime passed anti-Jewish laws and orchestrated a nationwide pogrom in November 1938. After Germany invaded Poland in September 1939, occupation authorities began to establish ghettos to segregate Jews. Following the invasion of the Soviet Union in June 1941, around 1.5 to 2 million Jews were shot by German forces and local collaborators.

Later in 1941 or early 1942, the highest levels of the German government decided to murder all Jews throughout Europe. Victims were deported by rail to extermination camps where, if they survived the journey, most were killed with poison gas. Other Jews continued to be employed in forced labor camps where many died from starvation, abuse or exhaustion[2] or used as test subjects in deadly medical experiments.[3] Although many Jews tried to escape, surviving in hiding was very difficult due to factors such as the lack of money to pay helpers and the risk of denunciation. The property, homes, and jobs belonging to murdered Jews were redistributed to the German occupiers and other non-Jews. Although the majority of Holocaust victims died in 1942, the killing continued at a lower rate until the end of the war in May 1945. Not all victims were Jews however, with millions killed for ethnic and ideological associations.

Many Jewish survivors emigrated outside of Europe after the war. A few Holocaust perpetrators faced criminal trials. Billions of dollars in reparations have been paid, although falling short of the Jews' losses. The Holocaust has also been commemorated in museums, memorials, and culture. It has become central to Western historical consciousness as a symbol of the ultimate human evil.
The Holocaust was the genocide of European Jews during World War II. Between 1941 and 1945, Nazi Germany and its collaborators systematically murdered some six million Jews across German-occupied Europe, around two-thirds of Europe's Jewish population. The murders were carried out primarily through mass shootings and poison gas in extermination camps, chiefly Auschwitz-Birkenau, Treblinka, Belzec, Sobibor, and Chełmno in occupied Poland.

The Nazis developed their ideology based on racism and pursuit of "living space" and seized power in early 1933. In an attempt to force all German Jews to emigrate, the regime passed anti-Jewish laws and orchestrated a nationwide pogrom in November 1938. After Germany invaded Poland in September 1939, occupation authorities began to establish ghettos to segregate Jews. Following the invasion of the Soviet Union in June 1941, around 1.5 to 2 million Jews were shot by German forces and local collaborators.

Later in 1941 or early 1942, the highest levels of the German government decided to murder all Jews throughout Europe. Victims were deported by rail to extermination camps where, if they survived the journey, most were killed with poison gas. Other Jews continued to be employed in forced labor camps where many died from starvation, abuse or exhaustion[2] or used as test subjects in deadly medical experiments.[3] Although many Jews tried to escape, surviving in hiding was very difficult due to factors such as the lack of money to pay helpers and the risk of denunciation. The property, homes, and jobs belonging to murdered Jews were redistributed to the German occupiers and other non-Jews. Although the majority of Holocaust victims died in 1942, the killing continued at a lower rate until the end of the war in May 1945. Not all victims were Jews however, with millions killed for ethnic and ideological associations.

Many Jewish survivors emigrated outside of Europe after the war. A few Holocaust perpetrators faced criminal trials. Billions of dollars in reparations have been paid, although falling short of the Jews' losses. The Holocaust has also been commemorated in museums, memorials, and culture. It has become central to Western historical consciousness as a symbol of the ultimate human evil.
The Holocaust was the genocide of European Jews during World War II. Between 1941 and 1945, Nazi Germany and its collaborators systematically murdered some six million Jews across German-occupied Europe, around two-thirds of Europe's Jewish population. The murders were carried out primarily through mass shootings and poison gas in extermination camps, chiefly Auschwitz-Birkenau, Treblinka, Belzec, Sobibor, and Chełmno in occupied Poland.

The Nazis developed their ideology based on racism and pursuit of "living space" and seized power in early 1933. In an attempt to force all German Jews to emigrate, the regime passed anti-Jewish laws and orchestrated a nationwide pogrom in November 1938. After Germany invaded Poland in September 1939, occupation authorities began to establish ghettos to segregate Jews. Following the invasion of the Soviet Union in June 1941, around 1.5 to 2 million Jews were shot by German forces and local collaborators.

Later in 1941 or early 1942, the highest levels of the German government decided to murder all Jews throughout Europe. Victims were deported by rail to extermination camps where, if they survived the journey, most were killed with poison gas. Other Jews continued to be employed in forced labor camps where many died from starvation, abuse or exhaustion[2] or used as test subjects in deadly medical experiments.[3] Although many Jews tried to escape, surviving in hiding was very difficult due to factors such as the lack of money to pay helpers and the risk of denunciation. The property, homes, and jobs belonging to murdered Jews were redistributed to the German occupiers and other non-Jews. Although the majority of Holocaust victims died in 1942, the killing continued at a lower rate until the end of the war in May 1945. Not all victims were Jews however, with millions killed for ethnic and ideological associations.

Many Jewish survivors emigrated outside of Europe after the war. A few Holocaust perpetrators faced criminal trials. Billions of dollars in reparations have been paid, although falling short of the Jews' losses. The Holocaust has also been commemorated in museums, memorials, and culture. It has become central to Western historical consciousness as a symbol of the ultimate human evil.

The Holocaust was the genocide of European Jews during World War II. Between 1941 and 1945, Nazi Germany and its collaborators systematically murdered some six million Jews across German-occupied Europe, around two-thirds of Europe's Jewish population. The murders were carried out primarily through mass shootings and poison gas in extermination camps, chiefly Auschwitz-Birkenau, Treblinka, Belzec, Sobibor, and Chełmno in occupied Poland.

The Nazis developed their ideology based on racism and pursuit of "living space" and seized power in early 1933. In an attempt to force all German Jews to emigrate, the regime passed anti-Jewish laws and orchestrated a nationwide pogrom in November 1938. After Germany invaded Poland in September 1939, occupation authorities began to establish ghettos to segregate Jews. Following the invasion of the Soviet Union in June 1941, around 1.5 to 2 million Jews were shot by German forces and local collaborators.

Later in 1941 or early 1942, the highest levels of the German government decided to murder all Jews throughout Europe. Victims were deported by rail to extermination camps where, if they survived the journey, most were killed with poison gas. Other Jews continued to be employed in forced labor camps where many died from starvation, abuse or exhaustion[2] or used as test subjects in deadly medical experiments.[3] Although many Jews tried to escape, surviving in hiding was very difficult due to factors such as the lack of money to pay helpers and the risk of denunciation. The property, homes, and jobs belonging to murdered Jews were redistributed to the German occupiers and other non-Jews. Although the majority of Holocaust victims died in 1942, the killing continued at a lower rate until the end of the war in May 1945. Not all victims were Jews however, with millions killed for ethnic and ideological associations.

Many Jewish survivors emigrated outside of Europe after the war. A few Holocaust perpetrators faced criminal trials. Billions of dollars in reparations have been paid, although falling short of the Jews' losses. The Holocaust has also been commemorated in museums, memorials, and culture. It has become central to Western historical consciousness as a symbol of the ultimate human evil.
        </div>
        <div className="flex flex-col border-2 border-black h-screen w-[20vw]">

        </div>
    </div>
  )
}
